### ISSUE TITLE
`make coverage` segfaults on Linux

### ISSUE THREAD

**Issue by dfellis** [uber/h3#3]
Hey @isaacbrodsky :) The `testCompact` test in code coverage mode currently segfaults in Linux (Kubuntu 17.04) on both gcc and clang.

I'll try to figure it out and fix it if I can, but you'll probably run into the same thing when you're getting coveralls set up, so I thought I'd give you a heads up.

```
damocles@Talyn:~/oss/h3(master)$ make coverage
[  1%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/algos.c.o
[  1%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/baseCells.c.o
[  1%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/bbox.c.o
[  2%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/coordijk.c.o
[  2%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/faceijk.c.o
[  2%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/geoCoord.c.o
[  3%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/h3Index.c.o
[  3%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/h3IndexFat.c.o
[  3%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/h3UniEdge.c.o
[  5%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/h3api.c.o
[  5%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/linkedGeo.c.o
[  5%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/mathExtensions.c.o
[  6%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/vec2d.c.o
[  6%] Building C object CMakeFiles/h3.1.dir/src/h3lib/lib/vertexGraph.c.o
[  6%] Linking C shared library lib/libh3.1.so
[  6%] Built target h3.1
[  6%] Building C object CMakeFiles/testH3ToGeoBoundary.dir/src/apps/testapps/testH3ToGeoBoundary.c.o
[  7%] Building C object CMakeFiles/testH3ToGeoBoundary.dir/src/apps/applib/lib/kml.c.o
[  7%] Building C object CMakeFiles/testH3ToGeoBoundary.dir/src/apps/applib/lib/test.c.o
[  7%] Building C object CMakeFiles/testH3ToGeoBoundary.dir/src/apps/applib/lib/utility.c.o
[  9%] Linking C executable bin/testH3ToGeoBoundary
[  9%] Built target testH3ToGeoBoundary
[  9%] Zeroing counters
Deleting all .da files in /home/damocles/oss/h3 and subdirectories
Done.
[  9%] Built target clean-coverage
[  9%] Running testH3ToGeoBoundary_coverage47
[  9%] Built target testH3ToGeoBoundary_coverage47
[ 10%] Building C object CMakeFiles/testLinkedGeo.dir/src/apps/testapps/testLinkedGeo.c.o
[ 10%] Building C object CMakeFiles/testLinkedGeo.dir/src/apps/applib/lib/kml.c.o
[ 10%] Building C object CMakeFiles/testLinkedGeo.dir/src/apps/applib/lib/test.c.o
[ 11%] Building C object CMakeFiles/testLinkedGeo.dir/src/apps/applib/lib/utility.c.o
[ 11%] Linking C executable bin/testLinkedGeo
[ 11%] Built target testLinkedGeo
[ 11%] Running testLinkedGeo_coverage92
[ 11%] Built target testLinkedGeo_coverage92
[ 12%] Building C object CMakeFiles/testH3SetToLinkedGeo.dir/src/apps/testapps/testH3SetToLinkedGeo.c.o
[ 12%] Building C object CMakeFiles/testH3SetToLinkedGeo.dir/src/apps/applib/lib/kml.c.o
[ 12%] Building C object CMakeFiles/testH3SetToLinkedGeo.dir/src/apps/applib/lib/test.c.o
[ 14%] Building C object CMakeFiles/testH3SetToLinkedGeo.dir/src/apps/applib/lib/utility.c.o
[ 14%] Linking C executable bin/testH3SetToLinkedGeo
[ 14%] Built target testH3SetToLinkedGeo
[ 14%] Running testH3SetToLinkedGeo_coverage90
[ 14%] Built target testH3SetToLinkedGeo_coverage90
[ 15%] Building C object CMakeFiles/testH3Api.dir/src/apps/testapps/testH3Api.c.o
[ 15%] Building C object CMakeFiles/testH3Api.dir/src/apps/applib/lib/kml.c.o
[ 15%] Building C object CMakeFiles/testH3Api.dir/src/apps/applib/lib/test.c.o
[ 16%] Building C object CMakeFiles/testH3Api.dir/src/apps/applib/lib/utility.c.o
[ 16%] Linking C executable bin/testH3Api
[ 16%] Built target testH3Api
[ 16%] Running testH3Api_coverage89
[ 16%] Built target testH3Api_coverage89
[ 18%] Building C object CMakeFiles/testH3ToParent.dir/src/apps/testapps/testH3ToParent.c.o
[ 18%] Building C object CMakeFiles/testH3ToParent.dir/src/apps/applib/lib/kml.c.o
[ 18%] Building C object CMakeFiles/testH3ToParent.dir/src/apps/applib/lib/test.c.o
[ 19%] Building C object CMakeFiles/testH3ToParent.dir/src/apps/applib/lib/utility.c.o
[ 19%] Linking C executable bin/testH3ToParent
[ 19%] Built target testH3ToParent
[ 19%] Running testH3ToParent_coverage84
[ 19%] Built target testH3ToParent_coverage84
[ 20%] Building C object CMakeFiles/testH3ToChildren.dir/src/apps/testapps/testH3ToChildren.c.o
[ 20%] Building C object CMakeFiles/testH3ToChildren.dir/src/apps/applib/lib/kml.c.o
[ 20%] Building C object CMakeFiles/testH3ToChildren.dir/src/apps/applib/lib/test.c.o
[ 22%] Building C object CMakeFiles/testH3ToChildren.dir/src/apps/applib/lib/utility.c.o
[ 22%] Linking C executable bin/testH3ToChildren
[ 22%] Built target testH3ToChildren
[ 22%] Running testH3ToChildren_coverage85
[ 22%] Built target testH3ToChildren_coverage85
[ 23%] Building C object CMakeFiles/testHexRanges.dir/src/apps/testapps/testHexRanges.c.o
[ 23%] Building C object CMakeFiles/testHexRanges.dir/src/apps/applib/lib/kml.c.o
[ 23%] Building C object CMakeFiles/testHexRanges.dir/src/apps/applib/lib/test.c.o
[ 24%] Building C object CMakeFiles/testHexRanges.dir/src/apps/applib/lib/utility.c.o
[ 24%] Linking C executable bin/testHexRanges
[ 24%] Built target testHexRanges
[ 24%] Running testHexRanges_coverage83
[ 24%] Built target testHexRanges_coverage83
[ 25%] Building C object CMakeFiles/testHexRing.dir/src/apps/testapps/testHexRing.c.o
[ 25%] Building C object CMakeFiles/testHexRing.dir/src/apps/applib/lib/kml.c.o
[ 25%] Building C object CMakeFiles/testHexRing.dir/src/apps/applib/lib/test.c.o
[ 27%] Building C object CMakeFiles/testHexRing.dir/src/apps/applib/lib/utility.c.o
[ 27%] Linking C executable bin/testHexRing
[ 27%] Built target testHexRing
[ 27%] Running testHexRing_coverage82
[ 27%] Built target testHexRing_coverage82
[ 28%] Building C object CMakeFiles/testKRing.dir/src/apps/testapps/testKRing.c.o
[ 28%] Building C object CMakeFiles/testKRing.dir/src/apps/applib/lib/kml.c.o
[ 28%] Building C object CMakeFiles/testKRing.dir/src/apps/applib/lib/test.c.o
[ 29%] Building C object CMakeFiles/testKRing.dir/src/apps/applib/lib/utility.c.o
[ 29%] Linking C executable bin/testKRing
[ 29%] Built target testKRing
[ 29%] Running testKRing_coverage81
[ 29%] Built target testKRing_coverage81
[ 29%] Running testH3ToGeoBoundary_coverage78
[ 29%] Built target testH3ToGeoBoundary_coverage78
[ 29%] Running testH3ToGeoBoundary_coverage77
[ 29%] Built target testH3ToGeoBoundary_coverage77
[ 31%] Running testH3ToGeoBoundary_coverage76
[ 31%] Built target testH3ToGeoBoundary_coverage76
[ 31%] Running testH3ToGeoBoundary_coverage74
[ 31%] Built target testH3ToGeoBoundary_coverage74
[ 31%] Running testH3ToGeoBoundary_coverage69
[ 31%] Built target testH3ToGeoBoundary_coverage69
[ 31%] Running testH3ToGeoBoundary_coverage68
[ 31%] Built target testH3ToGeoBoundary_coverage68
[ 31%] Running testH3ToGeoBoundary_coverage75
[ 31%] Built target testH3ToGeoBoundary_coverage75
[ 32%] Running testH3ToGeoBoundary_coverage67
[ 32%] Built target testH3ToGeoBoundary_coverage67
[ 32%] Running testH3ToGeoBoundary_coverage65
[ 32%] Built target testH3ToGeoBoundary_coverage65
[ 32%] Running testH3ToGeoBoundary_coverage63
[ 32%] Built target testH3ToGeoBoundary_coverage63
[ 32%] Running testH3ToGeoBoundary_coverage62
[ 32%] Built target testH3ToGeoBoundary_coverage62
[ 32%] Running testH3ToGeoBoundary_coverage60
[ 32%] Built target testH3ToGeoBoundary_coverage60
[ 32%] Building C object CMakeFiles/testCompact.dir/src/apps/testapps/testCompact.c.o
[ 33%] Building C object CMakeFiles/testCompact.dir/src/apps/applib/lib/kml.c.o
[ 33%] Building C object CMakeFiles/testCompact.dir/src/apps/applib/lib/test.c.o
[ 33%] Building C object CMakeFiles/testCompact.dir/src/apps/applib/lib/utility.c.o
[ 35%] Linking C executable bin/testCompact
[ 35%] Built target testCompact
[ 35%] Running testCompact_coverage80
Segmentation fault
CMakeFiles/testCompact_coverage80.dir/build.make:57: recipe for target 'CMakeFiles/testCompact_coverage80' failed
make[3]: *** [CMakeFiles/testCompact_coverage80] Error 139
CMakeFiles/Makefile2:1232: recipe for target 'CMakeFiles/testCompact_coverage80.dir/all' failed
make[2]: *** [CMakeFiles/testCompact_coverage80.dir/all] Error 2
CMakeFiles/Makefile2:1835: recipe for target 'CMakeFiles/coverage.dir/rule' failed
make[1]: *** [CMakeFiles/coverage.dir/rule] Error 2
Makefile:812: recipe for target 'coverage' failed
make: *** [coverage] Error 2
damocles@Talyn:~/oss/h3(master)$
```

**Comment by isaacbrodsky** [comment]
Hi David!

Thanks for the heads up. It looks like it's working for me on Ubuntu 16.04 with GCC 5.4.0. Clang doesn't work in that setup but it looks like an lcov <-> Clang issue, not a segfault. What version of GCC are you using?

I'll definitely take a look when as I setup coverage reporting.

**Comment by dfellis** [comment]
```
damocles@Talyn:~/oss/h3(master)$ gcc --version
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by dfellis** [comment]
Ran a gdb trace and I think I can fix this relatively quickly.

```
damocles@Talyn:~/oss/h3(master)$ gdb
GNU gdb (Ubuntu 8.0.1-0ubuntu1) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) file
No executable file now.
No symbol file now.
(gdb) file bin/testCompact
Reading symbols from bin/testCompact...done.
(gdb) run
Starting program: /home/damocles/oss/h3/bin/testCompact
TEST compact

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bbf38d in uncompact (compactedSet=0x60a020, numHexes=122, h3Set=0x0, maxHexes=122, res=0) at /home/damocles/oss/h3/src/h3lib/lib/h3Index.c:400
400	            h3Set[outOffset] = compactedSet[i];
(gdb) bt
#0  0x00007ffff7bbf38d in uncompact (compactedSet=0x60a020, numHexes=122, h3Set=0x0, maxHexes=122, res=0) at /home/damocles/oss/h3/src/h3lib/lib/h3Index.c:400
#1  0x0000000000401c86 in main (argc=1, argv=0x7fffffffdc58) at /home/damocles/oss/h3/src/apps/testapps/testCompact.c:90
(gdb)
```

**Comment by dfellis** [comment]
Found it. It was a silly typo when callocing the output memory.

```diff
damocles@Talyn:~/oss/h3(master)$ git diff
diff --git a/src/apps/testapps/testCompact.c b/src/apps/testapps/testCompact.c
index 9277469..eedc9f2 100644
--- a/src/apps/testapps/testCompact.c
+++ b/src/apps/testapps/testCompact.c
@@ -85,7 +85,7 @@ TEST(res0) {
     }

     H3Index* decompressed = calloc(
-        H3_EXPORT(maxUncompactSize)(compressed, hexCount, 9), sizeof(H3Index));
+        H3_EXPORT(maxUncompactSize)(compressed, hexCount, 0), sizeof(H3Index));
     int err2 =
         H3_EXPORT(uncompact)(compressed, hexCount, decompressed, hexCount, 0);
     t_assert(err2 == 0, "no error on uncompact");
```

**Comment by isaacbrodsky** [comment]
Thanks for fixing it!
